### PR TITLE
major refactor for specifying coupling fields and mapping route handles

### PR DESCRIPTION
**Pull request by mvertens**
major refactor of how coupling fields are specified and mapping route handles are created
a few other key changes are:

**field exchange:**
- a new cesm-specific directory, `cime_flds`, has been created that contains cesm specific field exchange information. This use to be contained in the `shr/ directory`. The vision is that the share directory and the mediator directory should not reference cesm specific data. There might be phases that are used by cesm - but should not be cesm-specific hard-wired information. 
- A new file `cime_flds/esmFlds.F90 `now encapsulates all of the information needed for the advertise phase as well as for _creation of route handles_ and _normalization_. 
- A completely modified shr/shr_nuopc_fldList_mod.F90 now contains the data types and methods that are used by `esmFlds.F90`

**mapping**
- A new file `mediator/map_mod.F90 ` contains new methods for creating all route handles needed in the mapping as well as the associated normalization factors. The necessary route handles are created using the information in `esmFlds.F90 `and done in a way so that only unique route handles are created and used. 
- The introduction of map_mod.F90 has resulted the removal of cesm-specific code in med.F90 for the generation of route handles. (med.F90 has now been shortened by ~400 loc).
- All mapping is currently done now using the new routine `med_map_FB_Regrid_Norm` rather than the previous calls to _shr_nuopc_methods_FB_Regrid_

**new esmf config variables rather than namelist variables**
- mapping files are now specified via esmf config variables and accessed in esmFlds.F90

** new logging **
- cleaned up logging output - cpl.log file is now med.log file and output is going there for mediator related info

** cleanup of time manager **

Test suite: 
differences relative to	the head of nuopcB

- SMS_Vnuopc.f19_g16.X.hobart_intel
  not	bfb due to differences in field ordering introduced in esmFlds.F90
- SMS_Vnuopc_Ld1.T31_g37_rx1.A.hobart_intel (bfb)
- SMS_Vnuopc_Ld2.ww3a.ADWAV.hobart_intel (bfb)
- SMS_Vnuopc_Ld3.f09_f09_mg16.ADLND.hobart_intel.drv-glcnec10 (bfb)
- SMS_Vnuopc_Ln5.T62_g37.DTEST.hobart_intel.cice-nuopc_cap (roundoff)
- SMS_Vnuopc_Ln5.f10_f10.F2000Nuopc.hobart_intel.cam-nuopc_cap (bfb)
- SMS_Vnuopc_Ln5.f10_f10.I2000Clm50SpNuopc.hobart_intel.clm-nuopc_cap (bfb)
- SMS_Vnuopc_Ln5.ne16_ne16_mg37.QPC4.hobart_intel.cam-nuopc_cap (bfb)

Also verified that the mom6 cap is working with this change.

The following new prognostic component branches need to be created:
https://svn-ccsm-models.cgd.ucar.edu/cam1/branch_tags/nuopc_cap_tags/nuopc_cap_n06_cam5_4_143
https://svn-ccsm-models.cgd.ucar.edu/clm2/branch_tags/nuopc_cap_tags/nuopc_cap_n05_clm4_5_16_r253
https://svn-ccsm-models.cgd.ucar.edu/cice/branch_tags/nuopc_cap_tags/nuopc_cap_n04_cice5_20171208

Test baseline: 
Test namelist changes: 
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Review by apcraig — COMMENTED** [review]
why does the fldListFr and fldListTo need to live in a shared module and why does the entire array of those things need to be exposed to individual models?  

Wondering if the hardcoded special shr_nuopc_fldList_type data in esmFlds.F90 is general enough.

Why aren't the xxx2yyy_zmapname placed into a 2d (ncomps,ncomps) array in esmFlds for extensibility.

The refactor of esmFlds seems to going the wrong direction.  Why are we manually loaded one field at a time into the fldList datatype without something in between (like the old colon delimited field lists).  In the long term, we are going to either be specifying field lists via namelist or we are going to have the model caps load up their names directly and we'll have synonyms loaded up into a dictionary.  Where is this routine called from?  If all components are sharing the same module data (not a good idea in general), then is it called from the driver?  NUOPC really wants each component to handle this separately for interoperability.  Where is the transferoffer set?

just fyi that there is a reason why __FILE__ is on a separate line.  it's possible that string will be long and break line length limits in some compilers.  by putting __FILE__ on a separate line, we gain 20 characters (or so).

**Comment by mvertens** [comment]
_why does the fldListFr and fldListTo need to live in a shared module and why does the entire array of those things need to be exposed to individual models?_

Before each component was passing in a colon delimited string of fields that lived in a _shared module_ in `shr_nuopc_flds_mod` and that string was then converted into the fldlist data type in shr_nuopc_fldList_fromflds. The entire list of colon delimited strings from each component was previously then also exposed to the individual models. The new approach is an intermediate step in making all of this info data drive via the introduction of a new data type that has all the necessary information for mapping and merging (the merging is not yet implemented) in it and all in one place and via an api rather than distributed throughout the code. 

_wondering if the hardcoded special shr_nuopc_fldList_type data in esmFlds.F90 is general enough._

It might not be. Its a first step to consolidating information that was spread out throughout the code into one place. Implementing automatic merging that is not dependent on a naming convention is the next step and might require generalization of the datatype. Since it has a clear API right now - this should be doable without a huge change to the code base.

**Comment by mvertens** [comment]
_just fyi that there is a reason why FILE is on a separate line. it's possible that string will be long and break line length limits in some compilers. by putting FILE on a separate line, we gain 20 characters (or so)._

Thanks for pointing this out. I have put in the reuse of shr_nuopc_methods_ChkErr to remove many extra lines of code. Is that problematic?

**Comment by mvertens** [comment]
_The refactor of esmFlds seems to going the wrong direction. Why are we manually loaded one field at a time into the fldList datatype without something in between (like the old colon delimited field lists). In the long term, we are going to either be specifying field lists via namelist or we are going to have the model caps load up their names directly and we'll have synonyms loaded up into a dictionary. Where is this routine called from? If all components are sharing the same module data (not a good idea in general), then is it called from the driver? NUOPC really wants each component to handle this separately for interoperability. Where is the transferoffer set?_

The main purpose behind this PR is to consolidate data that was spread throughout the code and often hard-wired into one module with the appropriate APIs and a new prototype datatype that also consolidated merging, mapping, and normalization. The next steps is to take this module and move to a data driven implementation. I think this is a logical set of steps that will take us in the right direction.

**Comment by theurich** [comment]
> > just fyi that there is a reason why FILE is on a separate line. it's possible that string will be long and break line length limits in some compilers. by putting FILE on a separate line, we gain 20 characters (or so).
> 
> Thanks for pointing this out. I have put in the reuse of shr_nuopc_methods_ChkErr to remove many extra lines of code. Is that problematic?

Will the shr_nuopc_methods_ChkErr() report the FILE and LINE information of where the error is actually happening? It is critical that this information be present in the error back trace for efficient debugging.

**Comment by mvertens** [comment]
I have verified that this is happening as part of my development. I also
checked this with Rocky yesterday - that wrapping the error code in
shr_nuopc_methods_ChkErr()  would be a good way to go.

**Review by rsdunlapiv — APPROVED** [review]
Changes look reasonable after code review with Mariana. One outstanding item to be resolved is how to remove CMEPS dependencies from MOM6 cap. This will be a follow on activity.

**Pull request merged**
