### PR TITLE
Nuopc b

### PR DESCRIPTION
**Pull request by mvertens**
Removal of MCT from grid generation and X compsets

This PR does the following:
1) Changes to xcpl_comps - removal of MCT for all xcpl_comps with nuopc driver interfaces
   - xshare has been changed to have mct/ and nuopc/ interfaces
     in the nuopc/ interaces there are NO references to mct - purely data arrays are passed
     the mct interfaces are simply the original xshare code
   - all nuopc interfaces (e.g. xatm_comp_nuopc.F90) have been changed to remove ALL references to MCT
   - the build process for xcpl_comps is changed so that xshare/nuopc is picked for the nuopc driver
     and xshare/mct is picked for the mct driver
   - added new method, shr_nuopc_methods_Print_FieldExchInfo, to replace the mct_avect_info routine previously
     called by the noupc interfaces
2) Removal of shr_nuopc_dmodel_mod
   - new routine shr_noupc_grid_mod.F90 has been introduced that duplicates the behavior of the grid/mesh
     generation in shr_nuopc_dmodel_mod but WITHOUT the need for MCT. The mesh generation routine has been
     tested for A, X, DLND and DWAV tests - but none of the other grid generation has been tested.
   - modified all data nuopc interfaces (e.g. datm_comp_nuopc.F90) to use the mesh routine in shr_nuopc_grid_mod.F90.
   - also moved data model share files to dshare - to be consistent with cime esmci master - in order to facilitate
     bringing the code up to date with cime master
3) Added new run sequence that removed the following if the ocean component is stub ocean
   - MED med_phases_accum_fast from the fast sequence
   - @86400   #ocean coupling step
         OCN -> MED :remapMethod=redist
         MED med_connectors_post_ocn2med
      @
3) Test run:

Test suite: The following tests were run:
   SMS.T31_g37_rx1.A.cheyenne_intel --driver nuopc (bfb with nuopcB)
   SMS.f09_f09_mg16.ADLND.cheyenne_intel.drv-glcnec10 --driver nuopc (bfb with nuopcB)
   SMS.f19_g16.X.cheyenne_intel --driver noupc (bfb with nuopcB)
   SMS.ww3a.ADWAV.yellowstone_intel --driver nuopcB (abort on finalization - broke totally in nuopcB)

Test baseline: nuopcB
Test namelist changes: see (3) above for different run sequence with SOCN
Test status: bfb
Fixes: None
User interface changes?: data_comps and xcpl_comps nuopc interfaces have changed
Code review:

### CODE REVIEW

**Review by apcraig — APPROVED** [review]
202 commits and 364 files changed.  I'll just approve for now and assume things are working OK.  Can always create issues later.

**Comment by mvertens** [comment]
Sounds good. Thanks.

**Comment by mvertens** [comment]
Something is very wrong with this merge. Please do not confirm the merge if
you have not already done so.

**Comment by apcraig** [comment]
My understanding is that I am to review the code changes, not to verify they are correct.  I decided to accept the changes as they are so extensive it is impossible to review.  If you want me to verify the changes, that's unclear.  If the PR doesn't look right, that should be caught when the PR is created.

**Comment by mvertens** [comment]
No - I did not want you to verify the changes. It looks like the PR is
trying to merge master to nuopcB - which is NOT what we want to do. Really
sorry for the confusion.

**Comment by mvertens** [comment]
Let me try to create another PR and make sure its correct.

**Review by apcraig — CHANGES_REQUESTED** [review]
Please review further.

**Pull request closed without merging**
