### PR TITLE
auto generation of run time sequence

### PR DESCRIPTION
**Pull request by mvertens**
new cesm.runconfig - auto-generation of run time sequence and attributes≠

1) There is a new directory structure to take the first steps in
   isolating the mediator code so that it can be used outside of CIME.
   The new src/drivers/nuopc directory structure is:

   cime_config
   cime_driver
   mediator
   shr

   No src/drivers/mct/main routines are being used. There is a new
   routine in cime_driver/cesm_init_mod.F90 that achieves the
   initialization that previously took place in
   cesm_components_mod.F90.

2) a cime_config directory has been created in
    src/drivers/nuopc_cime_config that now creates the namelist and
    cesm.runconfig separately for the nuopc driver.  The new
    cesm.runconfig now contains the seq_infodata_parms namelist group
    values that were previously in drv_in.  Also, the
    seq_infodata_mod.F90 that now appears in
    drivers/nuopc/shr/seq_infodata_mod.F90, has been modified accordingly.

3) A new argument --driver has been added to both create_test and create_newcase to use the nuopc driver cime_config directory.

   ./create_newcase .... --driver nuopc
   ./create_test .... --driver nuopc

   will create the the same test as the mct driver - BUT using the nuopc source code, interfaces and cime_config files

4) The stub models have are now no longer needed and are not listed in the CESM_components_list attribute in cesm.runconfig

5) The runSeq attribute that appears in CaseDocs is tailored to:
   - not contain any stub components
   - not have any MED->XXX or associate phases if XXX is NOT a prognostic component

   The code in the data models and mediator have been modified to
   account for a component not being prognostic. The key point is that
   the components should NOT have to set the prognostic or present
   flag using nuopc. This should all be set via the
   CESM_compononent_list and runSeq attributes that are created from the nuopc/cime_config/buildnml.

Test suite: Verified that following A compset does not change output netcdf files
 ./create_newcase --compset A --res f45_g37_rx1 --mach hobart --compiler intel --case A.nuopc --driver nuopc
Test baseline: nuopcB
Test namelist changes: new cesm.runconfig and less namelist groups in drv_in
Test status: bit for bit, roundoff

Fixes: None

User interface changes?: new src/drivers/nuopc/cime_config/

Code review: jedwards

### CODE REVIEW

**Comment by mvertens** [comment]
@apcraig - I have modified cesm.runconfig so that it no longer removes the phases for MED->XXX for non-prognostic components that are present. However, I still think we will need the following module variables that I introduced in med_internal_state.F90

```
mediator/med_internalstate_mod.F90:  logical :: medToAtm
mediator/med_internalstate_mod.F90:  logical :: medToOcn
mediator/med_internalstate_mod.F90:  logical :: medToIce
mediator/med_internalstate_mod.F90:  logical :: medToLnd
mediator/med_internalstate_mod.F90:  logical :: medToRof
mediator/med_internalstate_mod.F90:  logical :: medToWav
mediator/med_internalstate_mod.F90:  logical :: medToGlc
```
since I think the following type of calls in med_connectors.F90 will need this logical variable:

```
       if (medToAtm) then
          call med_connectors_diagnose(is_local%wrap%NState_AtmExp, is_local%wrap%atmcntr, "med_to_atm", rc=rc)
          if (shr_nuopc_methods_ChkErr(rc,__LINE__,u_FILE_u)) return
          call shr_nuopc_methods_CopyInfodataToState(infodata,is_local%wrap%NState_AtmExp,'cpl2atm',is_local%wrap%mpicom,rc)
          if (shr_nuopc_methods_ChkErr(rc,__LINE__,u_FILE_u)) return
          call shr_nuopc_methods_CopyInfodataToState(infodata,is_local%wrap%NState_AtmImp,'cpl2atm',is_local%wrap%mpicom,rc)
          if (shr_nuopc_methods_ChkErr(rc,__LINE__,u_FILE_u)) return
       end if
```

**Review by apcraig — COMMENTED** [review]
Why aren't we copying over the full set of compsets and pe layouts from mct to nuopc?
I don't think we should need the medToXXX logical flags.  The code should work fine with no fields connected.  If it doesn't, then we should change the implementation where there is a problem rather than use a higher level flag like this.  So, if med_connectors_diagnose and shr_nuopc_methods_CopyInfoDatatoState do not work with no fields, those methods should be fixed to make them work, and make them more usable and more robust rather than having to wrap their calls inside a logical, medtoXXX, that is precomputed and become problematic to extend and maintain.

**Comment by mvertens** [comment]
Could you please clarify what you mean by "Why aren't we copying over the
full set of compsets and pe layouts from mct to nuopc?"

**Comment by apcraig** [comment]
Regarding the compset and pe list, when I look at the config_compsets (src/drivers/nuopc/cime_config/config_compsets.xml) and config_pes files, it looks like just A, X, and S are defined and for pe layout it also looks pretty simple.  Why wouldn't we want the entire list of current compsets and pe layouts from the mct side?

**Comment by mvertens** [comment]
I am really confused. The only items in the driver cime_config is A, X and
S compsets. The fully active compsets are defined in $SRCROOT/cime_config
(where $SRCROOT is generally ./$CIMEROOT/../) - NOT in cime. This is true
for mct and will be true for nuopc. Does that clarify things?

**Comment by apcraig** [comment]
OK, that makes sense.  I keep forgetting that the compsets are 
distributed now.

tony.......

**Pull request merged**
